repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main, --branch, develop]
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        args: [src/]
        pass_filenames: false

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--config-file, .yamllint]

default_stages: [pre-commit]

ci:
  autofix_prs: false
